In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
website_sessions = pd.read_csv(r"C:\Users\USER\Downloads\website_sessions.csv")
website_sessions

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
0,1,2012-03-19 08:04:16,1,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
1,2,2012-03-19 08:16:49,2,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
2,3,2012-03-19 08:26:55,3,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
3,4,2012-03-19 08:37:33,4,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
4,5,2012-03-19 09:00:55,5,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
...,...,...,...,...,...,...,...,...,...
482323,403902,2014-12-25 20:14:44,340578,0,bsearch,nonbrand,b_ad_1,desktop,https://www.bsearch.com
482324,437478,2015-02-05 06:14:57,366374,0,bsearch,brand,b_ad_2,desktop,https://www.bsearch.com
482325,160096,2013-12-02 06:02:37,139857,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
482326,165839,2013-12-11 03:13:02,136249,1,bsearch,brand,b_ad_2,desktop,https://www.bsearch.com
482327,45930,2012-11-23 10:37:23,41795,0,bsearch,nonbrand,b_ad_1,desktop,https://www.bsearch.com

In [5]:
website_sessions[website_sessions.duplicated()]

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
472871,250346,2014-05-19 20:19:29,214747,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
472872,11137,2012-06-14 12:42:06,10443,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
472873,132221,2013-09-23 13:37:30,115614,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
472874,147437,2013-11-06 19:01:26,128501,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
472875,57997,2012-12-17 02:47:14,52867,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
...,...,...,...,...,...,...,...,...,...
482323,403902,2014-12-25 20:14:44,340578,0,bsearch,nonbrand,b_ad_1,desktop,https://www.bsearch.com
482324,437478,2015-02-05 06:14:57,366374,0,bsearch,brand,b_ad_2,desktop,https://www.bsearch.com
482325,160096,2013-12-02 06:02:37,139857,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
482326,165839,2013-12-11 03:13:02,136249,1,bsearch,brand,b_ad_2,desktop,https://www.bsearch.com
482327,45930,2012-11-23 10:37:23,41795,0,bsearch,nonbrand,b_ad_1,desktop,https://www.bsearch.com

In [6]:
unique_counts = pd.DataFrame.from_records([(col, website_sessions[col].nunique()) for col in website_sessions.columns],
                          columns=['Column_Name', 'Num_Unique']).sort_values(by=['Num_Unique'])
unique_counts

          Column_Name  Num_Unique
3   is_repeat_session           2
7         device_type           2
8        http_referer           3
5        utm_campaign           4
6         utm_content           6
4          utm_source          15
2             user_id      394318
1          created_at      470444
0  website_session_id      472871

In [7]:
website_sessions["utm_campaign"].value_counts()

utm_campaign
nonbrand            303026
brand                37088
desktop_targeted      5035
pilot                 4562
Name: count, dtype: int64

In [8]:
website_sessions["utm_content"].value_counts()

utm_content
g_ad_1         288391
b_ad_1          55957
g_ad_2          33999
b_ad_2           8095
social_ad_2      5699
social_ad_1      5206
Name: count, dtype: int64

In [10]:
website_sessions["utm_source"].value_counts()
website_sessions["utm_source"].unique()

array(['gsearch', 'Gsearch', 'GSEARCH', 'gsearch_ads', nan, 'nan_ads',
       'Bsearch', 'bsearch', 'NAN', 'Nan', 'BSEARCH', 'bsearch_ads',
       'socialbook', 'socialbook_ads', 'SOCIALBOOK', 'Socialbook'],
      dtype=object)

In [14]:
website_sessions.isnull().sum()

website_session_id         0
created_at                 0
user_id                    0
is_repeat_session          0
utm_source             75560
utm_campaign          132617
utm_content            84981
device_type                0
http_referer           40724
dtype: int64

In [16]:
website_sessions[website_sessions.utm_source.isnull()].describe(include="all")

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
count,75560.000000,75560,75560.000000,75560.000000,0,0,0,75560,39274
unique,NaN,73999,NaN,NaN,0,0,0,2,2
top,NaN,2014-04-12 21:57:31,NaN,NaN,NaN,NaN,NaN,desktop,https://www.gsearch.com
freq,NaN,2,NaN,NaN,NaN,NaN,NaN,46794,31856
mean,266202.808020,NaN,213321.029764,0.628534,NaN,NaN,NaN,NaN,NaN
std,129170.588739,NaN,103576.326031,0.483200,NaN,NaN,NaN,NaN,NaN
min,905.000000,NaN,27.000000,0.000000,NaN,NaN,NaN,NaN,NaN
25%,164069.500000,NaN,131075.750000,0.000000,NaN,NaN,NaN,NaN,NaN
50%,274778.000000,NaN,221263.500000,1.000000,NaN,NaN,NaN,NaN,NaN
75%,378908.500000,NaN,299663.500000,1.000000,NaN,NaN,NaN,NaN,NaN
max,472871.000000,NaN,394318.000000,1.000000,NaN,NaN,NaN,NaN,NaN

In [17]:
website_pd_views = pd.read_csv(r"C:\Users\USER\Downloads\website_pageviews.csv")
website_pd_views

,website_pageview_id,created_at,website_session_id,pageview_url
0,1,2012-03-19 08:04:16,1,/home
1,2,2012-03-19 08:16:49,2,/home
2,3,2012-03-19 08:26:55,3,/home
3,4,2012-03-19 08:37:33,4,/home
4,5,2012-03-19 09:00:55,5,/home
...,...,...,...,...
1188119,1188120,2015-03-19 07:57:32,472866,/shipping
1188120,1188121,2015-03-19 07:58:13,472870,/the-original-mr-fuzzy
1188121,1188122,2015-03-19 07:59:07,472866,/billing-2
1188122,1188123,2015-03-19 07:59:08,472871,/home
1188123,1188124,2015-03-19 07:59:32,472868,/the-original-mr-fuzzy

In [18]:
website_sessions["website_session_id"].value_counts()

website_session_id
98313     2
215820    2
201002    2
38702     2
50132     2
         ..
472867    1
472868    1
472869    1
472870    1
3         1
Name: count, Length: 472871, dtype: int64

In [23]:
website_sessions[website_sessions["website_session_id"]==38702]

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
38701,38702,2012-11-01 22:41:49,28648,1,NaN,NaN,NaN,mobile,NaN
479210,38702,2012-11-01 22:41:49,28648,1,NaN,NaN,NaN,mobile,NaN

In [25]:
website_sessions.duplicated().sum()

np.int64(9457)

In [28]:
print(f'Duplicates in records data: {website_sessions.duplicated().sum()}, ({np.round(100*website_sessions.duplicated().sum()/len(website_sessions),1)}%)')

Duplicates in records data: 9457, (2.0%)

In [29]:
website_sessions.drop_duplicates(keep="first",inplace=True)

In [30]:
website_sessions

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
0,1,2012-03-19 08:04:16,1,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
1,2,2012-03-19 08:16:49,2,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
2,3,2012-03-19 08:26:55,3,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
3,4,2012-03-19 08:37:33,4,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
4,5,2012-03-19 09:00:55,5,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
...,...,...,...,...,...,...,...,...,...
472866,472867,2015-03-19 07:49:25,394314,0,gsearch,brand,g_ad_2,desktop,https://www.gsearch.com
472867,472868,2015-03-19 07:54:36,394315,0,bsearch,nonbrand,b_ad_1,mobile,https://www.bsearch.com
472868,472869,2015-03-19 07:55:40,394316,0,gsearch,NaN,g_ad_1,mobile,https://www.gsearch.com
472869,472870,2015-03-19 07:56:29,394317,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
472870,472871,2015-03-19 07:59:08,394318,0,NaN,NaN,NaN,mobile,NaN

In [31]:
unique_counts = pd.DataFrame.from_records([(col, website_sessions[col].nunique()) for col in website_sessions.columns],
                          columns=['Column_Name', 'Num_Unique']).sort_values(by=['Num_Unique'])
unique_counts

          Column_Name  Num_Unique
3   is_repeat_session           2
7         device_type           2
8        http_referer           3
5        utm_campaign           4
6         utm_content           6
4          utm_source          15
2             user_id      394318
1          created_at      470444
0  website_session_id      472871

In [33]:
website_sessions.user_id.value_counts()

user_id
178119    4
73051     4
192234    4
180820    4
132198    4
         ..
394314    1
394315    1
394316    1
394317    1
4         1
Name: count, Length: 394318, dtype: int64

In [37]:
website_sessions[website_sessions["user_id"]==192234]

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
222886,222887,2014-04-02 10:59:26,192234,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
243325,243326,2014-05-07 21:05:23,192234,1,NaN,NaN,NaN,desktop,https://www.bsearch.com
246860,246861,2014-05-14 01:01:54,192234,1,bsearch,brand,b_ad_2,desktop,https://www.bsearch.com
250866,250867,2014-05-20 16:06:35,192234,1,Nan,NaN,NaN,mobile,https://www.gsearch.com

In [38]:
repeat_users = (
    website_sessions['user_id']
    .value_counts()
    .loc[lambda x: x > 1]
    .index
)

In [39]:
repeat_users

Index([178119,  73051, 192234, 180820, 132198, 110048, 185033,  44812,  95602,
       141242,
       ...
       390985, 391016, 391079, 391087, 391226, 391234, 391263, 391403, 391407,
       391434],
      dtype='int64', name='user_id', length=51270)

In [40]:
len(website_sessions)

472871

In [41]:
472871 - 51270

421601

In [42]:
website_sessions.user_id.nunique()

394318

In [43]:
website_sessions.columns

Index(['website_session_id', 'created_at', 'user_id', 'is_repeat_session',
       'utm_source', 'utm_campaign', 'utm_content', 'device_type',
       'http_referer'],
      dtype='object')

In [44]:
website_sessions["created_at"] = pd.to_datetime(website_sessions["created_at"])

In [45]:
website_sessions

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
0,1,2012-03-19 08:04:16,1,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
1,2,2012-03-19 08:16:49,2,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
2,3,2012-03-19 08:26:55,3,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
3,4,2012-03-19 08:37:33,4,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
4,5,2012-03-19 09:00:55,5,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
...,...,...,...,...,...,...,...,...,...
472866,472867,2015-03-19 07:49:25,394314,0,gsearch,brand,g_ad_2,desktop,https://www.gsearch.com
472867,472868,2015-03-19 07:54:36,394315,0,bsearch,nonbrand,b_ad_1,mobile,https://www.bsearch.com
472868,472869,2015-03-19 07:55:40,394316,0,gsearch,NaN,g_ad_1,mobile,https://www.gsearch.com
472869,472870,2015-03-19 07:56:29,394317,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
472870,472871,2015-03-19 07:59:08,394318,0,NaN,NaN,NaN,mobile,NaN

In [47]:
user_sessions = (
    website_sessions.groupby('user_id')['website_session_id']
      .nunique()
      .reset_index(name='session_count')
)

In [49]:
user_sessions.describe()

            user_id  session_count
count  394318.00000  394318.000000
mean   197159.50000       1.199212
std    113829.94606       0.604871
min         1.00000       1.000000
25%     98580.25000       1.000000
50%    197159.50000       1.000000
75%    295738.75000       1.000000
max    394318.00000       4.000000

In [50]:
repeat_users = user_sessions[user_sessions['session_count'] > 1]

In [51]:
repeat_users

        user_id  session_count
12           13              2
16           17              2
26           27              2
35           36              2
42           43              2
...         ...            ...
391233   391234              2
391262   391263              2
391402   391403              2
391406   391407              2
391433   391434              2

[51270 rows x 2 columns]

In [54]:
repeat_sessions = website_sessions[website_sessions['is_repeat_session'] == 1]
repeat_sessions

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
966,967,2012-03-25 23:06:28,489,1,gsearch,NaN,g_ad_2,desktop,https://www.gsearch.com
978,979,2012-03-26 02:40:21,604,1,gsearch,brand,g_ad_2,mobile,https://www.gsearch.com
1044,1045,2012-03-26 11:54:49,846,1,NaN,NaN,NaN,desktop,NaN
1050,1051,2012-03-26 12:48:41,152,1,nan_ads,NaN,NaN,desktop,NaN
1174,1175,2012-03-27 09:31:58,218,1,NaN,NaN,NaN,mobile,https://www.gsearch.com
...,...,...,...,...,...,...,...,...,...
472846,472847,2015-03-19 06:57:13,378178,1,NaN,NaN,NaN,mobile,https://www.gsearch.com
472852,472853,2015-03-19 07:28:48,331346,1,gsearch,NaN,g_ad_2,desktop,https://www.gsearch.com
472853,472854,2015-03-19 07:29:55,370617,1,gsearch,brand,g_ad_2,desktop,https://www.gsearch.com
472859,472860,2015-03-19 07:37:38,365493,1,gsearch,brand,g_ad_2,mobile,https://www.gsearch.com
472860,472861,2015-03-19 07:38:28,383375,1,NaN,NaN,NaN,desktop,NaN

In [56]:
website_pd_views

,website_pageview_id,created_at,website_session_id,pageview_url
0,1,2012-03-19 08:04:16,1,/home
1,2,2012-03-19 08:16:49,2,/home
2,3,2012-03-19 08:26:55,3,/home
3,4,2012-03-19 08:37:33,4,/home
4,5,2012-03-19 09:00:55,5,/home
...,...,...,...,...
1188119,1188120,2015-03-19 07:57:32,472866,/shipping
1188120,1188121,2015-03-19 07:58:13,472870,/the-original-mr-fuzzy
1188121,1188122,2015-03-19 07:59:07,472866,/billing-2
1188122,1188123,2015-03-19 07:59:08,472871,/home
1188123,1188124,2015-03-19 07:59:32,472868,/the-original-mr-fuzzy

In [59]:
orders = pd.read_csv(r"C:\Users\USER\Downloads\orders.csv")
orders

,order_id,created_at,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,20,20.0,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,104,104.0,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,147,147.0,1,1,49.99,19.49
3,4,2012-03-20 09:41:45,160,160.0,1,1,49.99,19.49
4,5,2012-03-20 11:28:15,177,177.0,1,1,49.99,19.49
...,...,...,...,...,...,...,...,...
32308,32309,2015-03-19 03:58:12,472795,394255.0,1,1,49.99,19.49
32309,32310,2015-03-19 04:10:43,472798,394257.0,4,1,29.99,9.49
32310,32311,2015-03-19 05:27:28,472809,394268.0,2,2,89.98,31.98
32311,32312,2015-03-19 05:35:57,472814,394273.0,4,1,29.99,9.49
32312,32313,2015-03-19 05:38:31,472818,386000.0,1,1,49.99,19.49

In [61]:
orders

,order_id,created_at,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,20,20.0,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,104,104.0,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,147,147.0,1,1,49.99,19.49
3,4,2012-03-20 09:41:45,160,160.0,1,1,49.99,19.49
4,5,2012-03-20 11:28:15,177,177.0,1,1,49.99,19.49
...,...,...,...,...,...,...,...,...
32308,32309,2015-03-19 03:58:12,472795,394255.0,1,1,49.99,19.49
32309,32310,2015-03-19 04:10:43,472798,394257.0,4,1,29.99,9.49
32310,32311,2015-03-19 05:27:28,472809,394268.0,2,2,89.98,31.98
32311,32312,2015-03-19 05:35:57,472814,394273.0,4,1,29.99,9.49
32312,32313,2015-03-19 05:38:31,472818,386000.0,1,1,49.99,19.49

In [63]:
orders.isnull().sum()

order_id                 0
created_at               0
website_session_id       0
user_id               1616
primary_product_id       0
items_purchased          0
price_usd                0
cogs_usd                 0
dtype: int64

In [64]:
unique_counts = pd.DataFrame.from_records([(col, orders[col].nunique()) for col in orders.columns],
                          columns=['Column_Name', 'Num_Unique']).sort_values(by=['Num_Unique'])
unique_counts

          Column_Name  Num_Unique
5     items_purchased           2
4  primary_product_id           4
7            cogs_usd          10
6           price_usd          20
3             user_id       30123
1          created_at       32299
2  website_session_id       32313
0            order_id       32313

In [65]:
website_sessions["user_id"].nunique()

394318

In [66]:
orders[orders["user_id"].isnull()]

,order_id,created_at,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
45,46,2012-03-29 16:11:05,1581,NaN,1,1,49.990000,19.49
56,57,2012-03-31 02:32:43,1802,NaN,1,1,49.990000,19.49
66,67,2012-04-02 17:17:42,2102,NaN,1,1,49.990000,19.49
97,98,2012-04-09 15:01:23,3247,NaN,1,1,49.990000,19.49
140,141,2012-04-22 16:58:22,4815,NaN,1,1,51.977855,19.49
...,...,...,...,...,...,...,...,...
32238,32239,2015-03-18 02:57:01,471758,NaN,1,1,49.990000,19.49
32255,32256,2015-03-18 10:51:31,471959,NaN,1,2,95.980000,33.98
32259,32260,2015-03-18 12:03:15,472054,NaN,1,1,49.990000,19.49
32287,32288,2015-03-18 18:10:53,472479,NaN,2,1,59.990000,22.49
32300,32301,2015-03-18 23:53:53,472709,NaN,4,1,29.990000,9.49

In [71]:
website_sessions[website_sessions["website_session_id"]==1581]

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
1580,1581,2012-03-29 15:51:13,1574,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com

In [74]:
new = pd.merge(orders,website_sessions[["user_id","website_session_id"]],on="website_session_id",how="inner")

In [76]:
new[new["user_id_x"].isnull()]

,order_id,created_at,website_session_id,user_id_x,primary_product_id,items_purchased,price_usd,cogs_usd,user_id_y
45,46,2012-03-29 16:11:05,1581,NaN,1,1,49.990000,19.49,1574
56,57,2012-03-31 02:32:43,1802,NaN,1,1,49.990000,19.49,1794
66,67,2012-04-02 17:17:42,2102,NaN,1,1,49.990000,19.49,2089
97,98,2012-04-09 15:01:23,3247,NaN,1,1,49.990000,19.49,3215
140,141,2012-04-22 16:58:22,4815,NaN,1,1,51.977855,19.49,4718
...,...,...,...,...,...,...,...,...,...
32238,32239,2015-03-18 02:57:01,471758,NaN,1,1,49.990000,19.49,393453
32255,32256,2015-03-18 10:51:31,471959,NaN,1,2,95.980000,33.98,393601
32259,32260,2015-03-18 12:03:15,472054,NaN,1,1,49.990000,19.49,338130
32287,32288,2015-03-18 18:10:53,472479,NaN,2,1,59.990000,22.49,394011
32300,32301,2015-03-18 23:53:53,472709,NaN,4,1,29.990000,9.49,394189

In [78]:
new

,order_id,created_at,website_session_id,user_id_x,primary_product_id,items_purchased,price_usd,cogs_usd,user_id_y
0,1,2012-03-19 10:42:46,20,20.0,1,1,49.99,19.49,20
1,2,2012-03-19 19:27:37,104,104.0,1,1,49.99,19.49,104
2,3,2012-03-20 06:44:45,147,147.0,1,1,49.99,19.49,147
3,4,2012-03-20 09:41:45,160,160.0,1,1,49.99,19.49,160
4,5,2012-03-20 11:28:15,177,177.0,1,1,49.99,19.49,177
...,...,...,...,...,...,...,...,...,...
32308,32309,2015-03-19 03:58:12,472795,394255.0,1,1,49.99,19.49,394255
32309,32310,2015-03-19 04:10:43,472798,394257.0,4,1,29.99,9.49,394257
32310,32311,2015-03-19 05:27:28,472809,394268.0,2,2,89.98,31.98,394268
32311,32312,2015-03-19 05:35:57,472814,394273.0,4,1,29.99,9.49,394273
32312,32313,2015-03-19 05:38:31,472818,386000.0,1,1,49.99,19.49,386000

In [72]:
order_items = pd.read_csv(r"C:\Users\USER\Downloads\order_items.csv")
order_items

,order_item_id,created_at,order_id,product_id,is_primary_item,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,1,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,2,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,3,1,1,49.99,19.49
3,4,2012-03-20 09:41:45,4,1,1,49.99,19.49
4,5,2012-03-20 11:28:15,5,1,1,49.99,19.49
...,...,...,...,...,...,...,...
40020,40021,2015-03-19 04:10:43,32310,4,1,29.99,9.49
40021,40022,2015-03-19 05:27:28,32311,2,1,59.99,22.49
40022,40023,2015-03-19 05:27:28,32311,4,0,29.99,9.49
40023,40024,2015-03-19 05:35:57,32312,4,1,29.99,9.49
40024,40025,2015-03-19 05:38:31,32313,1,1,49.99,19.49

In [77]:
order_refunds = pd.read_csv(r"C:\Users\USER\Downloads\order_item_refunds.csv")
order_refunds

,order_item_refund_id,created_at,order_item_id,order_id,refund_amount_usd
0,1,2012-04-06 11:32:43,57,57,49.99
1,2,2012-04-13 01:09:43,74,74,49.99
2,3,2012-04-15 07:03:48,71,71,49.99
3,4,2012-04-17 20:00:37,118,118,49.99
4,5,2012-04-22 20:53:49,116,116,49.99
...,...,...,...,...,...
1726,1727,2015-03-30 09:37:23,39950,32255,59.99
1727,1728,2015-03-30 21:33:51,39671,32049,49.99
1728,1729,2015-03-31 19:59:48,39729,32090,49.99
1729,1730,2015-04-01 03:54:48,39717,32079,59.99
1730,1731,2015-04-01 18:11:08,39947,32252,45.99